name: ssl_gnn
label: enctune
params:
  input_embed_dim: 19
  conv_layer_type: GCNConv
  conv_num_layers: 3
  conv_hidden_dim: 20
  gat_num_heads: 1
  conv_pool_method: max
  edge_active_ratio: 0.31681349876042875
  mlp_num_layers: 3
  mlp_hidden_dim: 128
  dropout: 0.1
  ssl_loss_type: 'SCL'
  tau: 0.1
  l1_weight: 0.0
  l2_weight: 0.0
