name: xgb_trainer
params:
  output_dir: ${output_dir}
  eval_metrics: &eval_metrics
    - name: rmse
      class: rmse
      params:
        column: 0
    - name: pearson_r
      class: pearson_r
      params:
        column: 0
  graph:
    writer:
      name: tensorboard
      params:
        log_dir: ${output_dir}
  test_save_output: true
