name: concept-kernels
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.12
  - pytorch-cuda=12.1
  - pytorch=2.4.1
  - torchaudio
  - torchvision
  - pyg=2.6.1
  - numpy=1.26.4
  - hydra-core=1.3.2
  - omegaconf=2.3.0
  - pandas=2.2.3
  - optuna=4.1.0
  - xgboost=2.1.3
  - jupyterlab
  - tqdm
  - pip
  - pip:
      - "--find-links https://data.pyg.org/whl/torch-2.4.0+cu121.html"
      - torch-scatter==2.1.2+pt24cu121
      - torch-sparse==0.6.18+pt24cu121
      - category_encoders==2.6.3
      - tensorboard==2.18.0
