name: ssl_ftt
label: enctune
params:
  token_bias: True
  n_layers: 1
  d_token: 64
  n_heads: 8
  d_ffn_factor: 2.5470567819536125
  attention_dropout: 0.0
  ffn_dropout: 0.0
  residual_dropout: 0.015549490200711086
  activation: reglu
  prenormalization: False
  initialization: xavier
  kv_compression: null
  kv_compression_sharing: null
  mlp_num_layers: 4
  mlp_hidden_dim: 128
  dropout: 0.1
  ssl_loss_type: 'SCL'
  tau: 0.1
  l1_weight: 0.0
  l2_weight: 0.0
