name: ssl_ftt
label: enctune
params:
  token_bias: True
  n_layers: 3
  d_token: 64
  n_heads: 8
  d_ffn_factor: 1.8385680277310115
  attention_dropout: 0.1562958272280253
  ffn_dropout: 0.09360779874287337
  residual_dropout: 0.0
  activation: reglu
  prenormalization: False
  initialization: xavier
  kv_compression: null
  kv_compression_sharing: null
  mlp_num_layers: 4
  mlp_hidden_dim: 128
  dropout: 0.1
  ssl_loss_type: 'SCL'
  tau: 0.1
  l1_weight: 0.0
  l2_weight: 0.0
