name: ssl_ftt
params:
  token_bias: true
  n_layers: 3
  d_token: 192
  n_heads: 8
  d_ffn_factor: 1.3333333333333333
  attention_dropout: 0.2
  ffn_dropout: 0.1
  residual_dropout: 0.0
  activation: "reglu"
  prenormalization: false
  initialization: "kaiming"
  kv_compression: null
  kv_compression_sharing: null
  mlp_num_layers: 4
  mlp_hidden_dim: 128
  dropout: 0.1
  ssl_loss_type: 'SCL'
  tau: 0.1
  num_swap_reg: 'fixcorr'
  l1_weight: 0.0
  l2_weight: 0.0
