name: ssl_ftt
label: enctune
params:
  token_bias: True
  n_layers: 4
  d_token: 128
  n_heads: 8
  d_ffn_factor: 1.51013367313388
  attention_dropout: 0.21870486718364096
  ffn_dropout: 0.46573288758790965
  residual_dropout: 0.0
  activation: reglu
  prenormalization: False
  initialization: xavier
  kv_compression: null
  kv_compression_sharing: null
  mlp_num_layers: 4
  mlp_hidden_dim: 128
  dropout: 0.1
  ssl_loss_type: 'SCL'
  tau: 0.1
  l1_weight: 0.0
  l2_weight: 0.0
