name: ssl_ftt
label: enctune
params:
  token_bias: True
  n_layers: 2
  d_token: 128
  n_heads: 8
  d_ffn_factor: 2.046855308022992
  attention_dropout: 0.1932257689528396
  ffn_dropout: 0.42797444251883043
  residual_dropout: 0.0
  activation: reglu
  prenormalization: False
  initialization: xavier
  kv_compression: null
  kv_compression_sharing: null
  mlp_num_layers: 4
  mlp_hidden_dim: 128
  dropout: 0.1
  ssl_loss_type: 'SCL'
  tau: 0.1
  l1_weight: 0.0
  l2_weight: 0.0
