name: gnn_baseline
label: gatconcept
params:
  input_embed_dim: 128
  conv_layer_type: 'GATConceptConv'
  conv_num_layers: 2
  conv_hidden_dim: 64
  concept_proj_dim: 8
  gat_num_heads: 3
  conv_pool_method: 'max'
  edge_active_ratio: 0.3
  mlp_num_layers: 3
  mlp_hidden_dim: 128
  dropout: 0.1
  l1_weight: 0.0
  l2_weight: 0.0
