defaults:
  - dataset: talent/communities_and_crime
  - model: ssl_ftt
  - trainer: ssl_finetune
  - search: ssl_ftt
  - _self_

seed: 0
phase: finetune
test: false
test_all_split: true
label: ""
pretrain_dir: results/{dataset_name}/{model_name}/pretrain
output_dir: results/{dataset_name}/{model_name}/${search.name}

dataset:
  data_common:
    use_onehot: true
trainer:
  params:
    freeze_encoder: false

hydra:
  output_subdir: null
  run:
    dir: results
  job_logging:
    version: 1
    disable_existing_loggers: false
    root:
      handlers: []
